// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: waves.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "waves";

export interface CreateWaveRequest {
  content: string;
}

export interface GetWavesRequest {
  limit: number;
  offset: number;
}

export interface GetWavesResponse {
  waves: Wave[];
}

export interface Wave {
  waveId: string;
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetWaveRequest {
  waveId: string;
}

export interface DeleteWaveRequest {
  waveId: string;
}

export interface DeleteWaveResponse {
  success: boolean;
}

export const WAVES_PACKAGE_NAME = "waves";

export interface WavesServiceClient {
  createWave(request: CreateWaveRequest): Observable<Wave>;

  getWave(request: GetWaveRequest): Observable<Wave>;

  getWaves(request: GetWavesRequest): Observable<GetWavesResponse>;

  deleteWave(request: DeleteWaveRequest): Observable<DeleteWaveResponse>;
}

export interface WavesServiceController {
  createWave(request: CreateWaveRequest): Promise<Wave> | Observable<Wave> | Wave;

  getWave(request: GetWaveRequest): Promise<Wave> | Observable<Wave> | Wave;

  getWaves(request: GetWavesRequest): Promise<GetWavesResponse> | Observable<GetWavesResponse> | GetWavesResponse;

  deleteWave(
    request: DeleteWaveRequest,
  ): Promise<DeleteWaveResponse> | Observable<DeleteWaveResponse> | DeleteWaveResponse;
}

export function WavesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWave", "getWave", "getWaves", "deleteWave"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WavesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WavesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WAVES_SERVICE_NAME = "WavesService";
