// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: waves.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'waves';

export interface CreateWaveRequest {
    content: string;
}

export interface CreateWaveResponse {
    waveId: string;
}

export interface GetWaveRequest {
    waveId: string;
}

export interface GetWaveResponse {
    content: string;
    createdAt: string;
}

export const WAVES_PACKAGE_NAME = 'waves';

export interface WavesServiceClient {
    createWave(request: CreateWaveRequest): Observable<CreateWaveResponse>;

    getWave(request: GetWaveRequest): Observable<GetWaveResponse>;
}

export interface WavesServiceController {
    createWave(
        request: CreateWaveRequest
    ): Promise<CreateWaveResponse> | Observable<CreateWaveResponse> | CreateWaveResponse;

    getWave(request: GetWaveRequest): Promise<GetWaveResponse> | Observable<GetWaveResponse> | GetWaveResponse;
}

export function WavesServiceControllerMethods() {
    return function (constructor: Function) {
        const grpcMethods: string[] = ['createWave', 'getWave'];
        for (const method of grpcMethods) {
            const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
            GrpcMethod('WavesService', method)(constructor.prototype[method], method, descriptor);
        }
        const grpcStreamMethods: string[] = [];
        for (const method of grpcStreamMethods) {
            const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
            GrpcStreamMethod('WavesService', method)(constructor.prototype[method], method, descriptor);
        }
    };
}

export const WAVES_SERVICE_NAME = 'WavesService';
